---
- hosts: localhost
  tasks:
  - name: Set vars from environments
    set_fact:
      winc_node_ip: "{{ lookup('env', 'WINC_NODE_IP') }}"
      winc_node_user: "{{ lookup('env', 'WINC_NODE_USER') }}"
      winc_node_password: "{{ lookup('env', 'WINC_NODE_PASSWORD') }}"
      cluster_address: "{{ lookup('env', 'CLUSTER_ADDRESS') }}"
  - block:
    - assert:
        that:
          - winc_node_ip != ""
          - winc_node_user != ""
          - winc_node_password != ""
          - cluster_address != ""

  - name: Inventory generation
    template: 
      src: inventory.j2
      dest: inventory