---
- hosts: localhost
  tasks:
  - name: List all nodes
    shell: |
      oc get nodes -o wide
    register: nodes_status
  - debug: msg="{{ nodes_status.stdout_lines }}"

  - name: List all operator status
    shell: |
      oc get co
    register: operators_status
  - debug: msg="{{ operators_status.stdout_lines }}"